package system

import (
	"context"
	"fmt"
	"sort"
	"strings"
	"sync"
)

// RealMaintenance schedules recurring maintenance jobs as
// systemd .timer + .service unit pairs. It is the production
// implementation behind the Maintenance interface.
//
// On install:
//   - Renders <name>.service (Type=oneshot) with ExecStart=<command>
//     and one Environment= line per env entry.
//   - Renders <name>.timer with the translated OnCalendar= expression
//     and Persistent=true so missed runs catch up after downtime.
//   - Daemon-reloads, then enables + starts the timer.
//
// On remove:
//   - Stops + disables the timer (best-effort), removes both unit
//     files, and daemon-reloads.
//
// ListJobs is backed by a JSON ledger at MaintenanceStateFile. We
// could instead parse `systemctl list-unit-files`, but that would
// either bloat the Systemctl interface or shell out a second time;
// the ledger keeps everything inside the existing seam.
type RealMaintenance struct {
	Systemctl Systemctl

	// MaintenanceStateFile overrides the JSON ledger path. Empty
	// means DefaultMaintenanceStateFile.
	MaintenanceStateFile string

	storeMu sync.Mutex
	store   *maintenanceStore
}

// NewRealMaintenance constructs a RealMaintenance bound to the given
// Systemctl. The ledger path defaults to DefaultMaintenanceStateFile.
func NewRealMaintenance(s Systemctl) *RealMaintenance {
	return &RealMaintenance{
		Systemctl: s,
		store:     newMaintenanceStore(""),
	}
}

// stateStore returns the store, lazily reinitialising it if the caller
// overrode MaintenanceStateFile after construction. Safe for
// concurrent callers.
func (r *RealMaintenance) stateStore() *maintenanceStore {
	r.storeMu.Lock()
	defer r.storeMu.Unlock()
	if r.store == nil || (r.MaintenanceStateFile != "" && r.store.Path != r.MaintenanceStateFile) {
		r.store = newMaintenanceStore(r.MaintenanceStateFile)
	}
	return r.store
}

// translateSchedule converts the canonical schedule keywords to a
// systemd OnCalendar= expression. Anything unknown is passed through
// verbatim, which lets operators specify any valid OnCalendar string
// (e.g., "Mon *-*-* 03:00:00") without code changes.
func translateSystemdSchedule(schedule string) string {
	switch strings.TrimSpace(schedule) {
	case ScheduleEvery15m:
		return "*:0/15"
	case ScheduleDaily:
		return "daily"
	case "hourly":
		return "hourly"
	default:
		return schedule
	}
}

// renderServiceUnit produces the .service unit body. We sort env keys
// so the output is deterministic — the ledger and the unit file should
// agree byte-for-byte across re-installs.
func renderSystemdServiceUnit(name, command string, env map[string]string) string {
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Auto-generated by radius-manager-api.\n")
	b.WriteString("# Edits will be overwritten — modify the manager template instead.\n")
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=radius-manager maintenance job %s\n", name)
	b.WriteString("After=network.target\n")
	b.WriteString("\n[Service]\n")
	b.WriteString("Type=oneshot\n")
	fmt.Fprintf(&b, "ExecStart=%s\n", command)
	for _, k := range keys {
		fmt.Fprintf(&b, "Environment=%s=%s\n", k, env[k])
	}
	return b.String()
}

// renderTimerUnit produces the .timer unit body. Persistent=true makes
// the timer fire on next boot if the box was off when the schedule
// elapsed (matters for laptops; harmless on always-on servers).
func renderSystemdTimerUnit(name, onCalendar string) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by radius-manager-api.\n")
	b.WriteString("# Edits will be overwritten — modify the manager template instead.\n")
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=Timer for radius-manager maintenance job %s\n", name)
	b.WriteString("\n[Timer]\n")
	fmt.Fprintf(&b, "Unit=%s.service\n", name)
	fmt.Fprintf(&b, "OnCalendar=%s\n", onCalendar)
	b.WriteString("Persistent=true\n")
	b.WriteString("\n[Install]\n")
	b.WriteString("WantedBy=timers.target\n")
	return b.String()
}

// InstallJob renders the .service + .timer pair, writes them, then
// daemon-reloads and enables/starts the timer. Idempotent — re-installing
// the same name overwrites the previous units.
func (r *RealMaintenance) InstallJob(ctx context.Context, name, schedule, command string, env map[string]string) error {
	if name == "" {
		return fmt.Errorf("maintenance: empty job name")
	}
	if command == "" {
		return fmt.Errorf("maintenance: install %q: empty command", name)
	}

	onCalendar := translateSystemdSchedule(schedule)
	serviceUnit := renderSystemdServiceUnit(name, command, env)
	timerUnit := renderSystemdTimerUnit(name, onCalendar)

	serviceName := name + ".service"
	timerName := name + ".timer"

	if err := r.Systemctl.WriteUnit(ctx, serviceName, serviceUnit); err != nil {
		return fmt.Errorf("maintenance: write %s: %w", serviceName, err)
	}
	if err := r.Systemctl.WriteUnit(ctx, timerName, timerUnit); err != nil {
		return fmt.Errorf("maintenance: write %s: %w", timerName, err)
	}
	if err := r.Systemctl.DaemonReload(ctx); err != nil {
		return fmt.Errorf("maintenance: daemon-reload after installing %s: %w", name, err)
	}
	if err := r.Systemctl.Enable(ctx, timerName); err != nil {
		return fmt.Errorf("maintenance: enable %s: %w", timerName, err)
	}
	if err := r.Systemctl.Start(ctx, timerName); err != nil {
		return fmt.Errorf("maintenance: start %s: %w", timerName, err)
	}

	if err := r.stateStore().upsert(name, maintenanceStateEntry{
		Schedule: schedule,
		Command:  command,
		Env:      env,
	}); err != nil {
		return fmt.Errorf("maintenance: persist ledger entry %s: %w", name, err)
	}
	return nil
}

// RemoveJob tears down the .timer and .service. The Stop call is
// best-effort: a timer that wasn't running yet would error here, but
// that doesn't change the desired end-state.
func (r *RealMaintenance) RemoveJob(ctx context.Context, name string) error {
	if name == "" {
		return fmt.Errorf("maintenance: empty job name")
	}
	timerName := name + ".timer"
	serviceName := name + ".service"

	// Best-effort stop — ignore failure.
	_ = r.Systemctl.Stop(ctx, timerName)

	// Disable: ignore "not enabled" errors so this stays idempotent.
	// The Systemctl interface doesn't differentiate, so we swallow
	// disable errors entirely. The subsequent RemoveUnit would still
	// surface a real problem.
	_ = r.Systemctl.Disable(ctx, timerName)

	if err := r.Systemctl.RemoveUnit(ctx, timerName); err != nil {
		return fmt.Errorf("maintenance: remove %s: %w", timerName, err)
	}
	if err := r.Systemctl.RemoveUnit(ctx, serviceName); err != nil {
		return fmt.Errorf("maintenance: remove %s: %w", serviceName, err)
	}
	if err := r.Systemctl.DaemonReload(ctx); err != nil {
		return fmt.Errorf("maintenance: daemon-reload after removing %s: %w", name, err)
	}
	if err := r.stateStore().remove(name); err != nil {
		return fmt.Errorf("maintenance: drop ledger entry %s: %w", name, err)
	}
	return nil
}

// ListJobs returns the sorted set of job names recorded in the ledger.
func (r *RealMaintenance) ListJobs(_ context.Context) ([]string, error) {
	return r.stateStore().list()
}
