package system

import (
	"context"
	"fmt"
	"sort"
	"strings"
	"sync"
)

// SupervisordMaintenance schedules recurring maintenance jobs by
// writing a wrapper supervisord program that loops the command with
// a sleep between iterations. Used by the Docker dev stack where
// systemd is not available.
//
// The translation is intentionally crude: supervisord has no native
// scheduling, so "every 15m" becomes
//
//	bash -c 'while true; do <command> || true; sleep 900; done'
//
// with autostart=true and autorestart=true. The `|| true` prevents a
// transient failure from killing the loop (autorestart would bring it
// back, but that adds log noise and respawn delay).
//
// Calls flow through SupervisordSystemctl underneath: WriteUnit writes
// the [program:<name>] config, RemoveUnit deletes it. We pass a
// .service-suffixed name because SupervisordSystemctl strips it via
// programName().
type SupervisordMaintenance struct {
	Systemctl Systemctl

	// MaintenanceStateFile overrides the JSON ledger path. Empty
	// means DefaultMaintenanceStateFile. Same semantics as
	// RealMaintenance.
	MaintenanceStateFile string

	storeMu sync.Mutex
	store   *maintenanceStore
}

// NewSupervisordMaintenance constructs a SupervisordMaintenance bound
// to the given Systemctl (typically a *SupervisordSystemctl).
func NewSupervisordMaintenance(s Systemctl) *SupervisordMaintenance {
	return &SupervisordMaintenance{
		Systemctl: s,
		store:     newMaintenanceStore(""),
	}
}

// stateStore returns the store, lazily reinitialising it if the caller
// overrode MaintenanceStateFile after construction. Safe for
// concurrent callers.
func (m *SupervisordMaintenance) stateStore() *maintenanceStore {
	m.storeMu.Lock()
	defer m.storeMu.Unlock()
	if m.store == nil || (m.MaintenanceStateFile != "" && m.store.Path != m.MaintenanceStateFile) {
		m.store = newMaintenanceStore(m.MaintenanceStateFile)
	}
	return m.store
}

// translateSupervisordSchedule maps the canonical schedule keywords to
// a sleep duration in seconds. Anything unknown returns 0 + an error
// because supervisord can't approximate, e.g., "Mon *-*-* 03:00:00"
// without a real cron-like daemon.
func translateSupervisordSchedule(schedule string) (int, error) {
	switch strings.TrimSpace(schedule) {
	case ScheduleEvery15m:
		return 900, nil
	case ScheduleDaily:
		return 86400, nil
	case "hourly":
		return 3600, nil
	default:
		return 0, fmt.Errorf("supervisord maintenance: unsupported schedule %q (only %q, %q, and \"hourly\" are supported)",
			schedule, ScheduleEvery15m, ScheduleDaily)
	}
}

// renderSupervisordProgram produces the [program:<name>] block. The
// command is wrapped in `bash -c 'while true; do … || true; sleep N; done'`
// so a single bad run doesn't take the program out of service.
//
// Env entries become a single environment= line in supervisord's
// "KEY=VALUE,KEY=VALUE" format. Values are wrapped in double-quotes
// to tolerate spaces and commas; literal " inside values is escaped.
func renderSupervisordProgram(name, command string, sleepSeconds int, env map[string]string) string {
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	// Inner command: `<command> || true; sleep N`.
	// Outer wrapper: `bash -c 'while true; do …; done'`.
	// Single-quote literal `'` inside command is escaped via the
	// classic '\'' sandwich so the final shell argument stays single-quoted.
	escapedCmd := strings.ReplaceAll(command, "'", `'\''`)
	loopBody := fmt.Sprintf(`while true; do %s || true; sleep %d; done`, escapedCmd, sleepSeconds)
	wrapped := fmt.Sprintf(`bash -c '%s'`, loopBody)

	var b strings.Builder
	fmt.Fprintf(&b, "; Auto-generated by radius-manager-api maintenance scheduler.\n")
	fmt.Fprintf(&b, "; Edits will be overwritten — modify the manager template instead.\n")
	fmt.Fprintf(&b, "[program:%s]\n", name)
	fmt.Fprintf(&b, "command=%s\n", wrapped)
	b.WriteString("autostart=true\n")
	b.WriteString("autorestart=true\n")
	b.WriteString("startsecs=0\n")
	b.WriteString("stopasgroup=true\n")
	b.WriteString("killasgroup=true\n")
	fmt.Fprintf(&b, "stdout_logfile=/var/log/supervisor/%s.out.log\n", name)
	fmt.Fprintf(&b, "stderr_logfile=/var/log/supervisor/%s.err.log\n", name)

	if len(keys) > 0 {
		parts := make([]string, 0, len(keys))
		for _, k := range keys {
			v := strings.ReplaceAll(env[k], `"`, `\"`)
			parts = append(parts, fmt.Sprintf(`%s="%s"`, k, v))
		}
		fmt.Fprintf(&b, "environment=%s\n", strings.Join(parts, ","))
	}
	return b.String()
}

// InstallJob renders the supervisord program and writes it via the
// underlying SupervisordSystemctl. Note that SupervisordSystemctl.WriteUnit
// expects systemd-formatted input by default — we bypass that by writing
// the program block directly through the Systemctl seam, which our
// concrete SupervisordSystemctl does NOT do. So we hand-write via the
// Systemctl interface differently:
//
// Actually, the cleanest path is to NOT go through SupervisordSystemctl.WriteUnit
// (which parses systemd). Instead we wrap a thin systemd-flavored unit
// that SupervisordSystemctl.WriteUnit can parse — but that loses all
// the loop scheduling. So we synthesize a [Service] section whose
// ExecStart is the bash-c wrapper. SupervisordSystemctl.WriteUnit will
// translate that into a [program:...] block with `command=<bash-c…>`.
// That gives us the sleep loop with no special-casing on either side.
func (m *SupervisordMaintenance) InstallJob(ctx context.Context, name, schedule, command string, env map[string]string) error {
	if name == "" {
		return fmt.Errorf("maintenance: empty job name")
	}
	if command == "" {
		return fmt.Errorf("maintenance: install %q: empty command", name)
	}

	sleepSeconds, err := translateSupervisordSchedule(schedule)
	if err != nil {
		return err
	}

	unit := renderSupervisordCompatUnit(name, command, sleepSeconds, env)

	if err := m.Systemctl.WriteUnit(ctx, name+".service", unit); err != nil {
		return fmt.Errorf("maintenance: write supervisord program %s: %w", name, err)
	}
	if err := m.Systemctl.DaemonReload(ctx); err != nil {
		return fmt.Errorf("maintenance: supervisorctl reread/update for %s: %w", name, err)
	}
	// Start is best-effort: the supervisord daemon may already have
	// auto-started it via reread/update. If the program is already
	// RUNNING, supervisorctl start returns an error we want to swallow.
	_ = m.Systemctl.Start(ctx, name+".service")

	if err := m.stateStore().upsert(name, maintenanceStateEntry{
		Schedule: schedule,
		Command:  command,
		Env:      env,
	}); err != nil {
		return fmt.Errorf("maintenance: persist ledger entry %s: %w", name, err)
	}
	return nil
}

// renderSupervisordCompatUnit emits a minimal systemd-format unit whose
// [Service] section contains the wrapped sleep-loop. Feeding this
// through SupervisordSystemctl.WriteUnit produces a working
// [program:<name>] configuration with `command=<bash-c …>`.
//
// Env entries are NOT injected as Environment= lines (SupervisordSystemctl
// doesn't translate those to supervisord's environment= directive).
// Instead we encode them inline into the bash wrapper as `KEY=VAL`
// prefixes so the child process inherits them.
func renderSupervisordCompatUnit(name, command string, sleepSeconds int, env map[string]string) string {
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	envPrefix := ""
	for _, k := range keys {
		// shell-quote the value with single quotes; escape literal '.
		v := strings.ReplaceAll(env[k], "'", `'\''`)
		envPrefix += fmt.Sprintf("%s='%s' ", k, v)
	}

	escapedCmd := strings.ReplaceAll(command, "'", `'\''`)
	loopBody := fmt.Sprintf(`while true; do %s%s || true; sleep %d; done`, envPrefix, escapedCmd, sleepSeconds)
	wrapped := fmt.Sprintf(`bash -c '%s'`, loopBody)

	var b strings.Builder
	b.WriteString("# Auto-generated by radius-manager-api supervisord maintenance scheduler.\n")
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=radius-manager maintenance job %s\n", name)
	b.WriteString("\n[Service]\n")
	b.WriteString("User=root\n")
	fmt.Fprintf(&b, "ExecStart=%s\n", wrapped)
	b.WriteString("Restart=always\n")
	return b.String()
}

// RemoveJob stops the program and deletes its conf. Idempotent —
// SupervisordSystemctl.Stop swallows the "not running" case and
// RemoveUnit ignores missing files.
func (m *SupervisordMaintenance) RemoveJob(ctx context.Context, name string) error {
	if name == "" {
		return fmt.Errorf("maintenance: empty job name")
	}
	unitName := name + ".service"

	// Best-effort stop. SupervisordSystemctl.Stop already treats
	// "not running" / "no such process" as non-error.
	_ = m.Systemctl.Stop(ctx, unitName)

	if err := m.Systemctl.RemoveUnit(ctx, unitName); err != nil {
		return fmt.Errorf("maintenance: remove supervisord program %s: %w", name, err)
	}
	if err := m.Systemctl.DaemonReload(ctx); err != nil {
		return fmt.Errorf("maintenance: supervisorctl reread/update after removing %s: %w", name, err)
	}
	if err := m.stateStore().remove(name); err != nil {
		return fmt.Errorf("maintenance: drop ledger entry %s: %w", name, err)
	}
	return nil
}

// ListJobs returns the sorted set of job names recorded in the ledger.
func (m *SupervisordMaintenance) ListJobs(_ context.Context) ([]string, error) {
	return m.stateStore().list()
}
