package system

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// SupervisordSystemctl is a Systemctl implementation that targets
// supervisord(8) instead of systemd. It is used by the Docker dev stack
// (and could be reused on any non-systemd host) to run per-instance
// freeradius-api processes without requiring a systemd PID 1.
//
// Translation strategy:
//
//   - WriteUnit parses a small subset of the systemd unit format that
//     internal/manager.renderAPIServiceUnit emits (WorkingDirectory,
//     ExecStart, User, Restart=always) and writes an equivalent
//     [program:<name>] section to ConfDir/<name>.conf.
//   - DaemonReload runs `supervisorctl reread && supervisorctl update`
//     so newly-written configs are picked up.
//   - Enable/Disable are no-ops because supervisord doesn't have a
//     separate "enabled" concept (autorestart=true is set in WriteUnit
//     so the program comes back on supervisord restart).
//   - Start/Stop/Restart map 1:1 to the same supervisorctl verbs.
//   - IsActive parses `supervisorctl status <name>` for "RUNNING".
//   - RemoveUnit deletes the conf file. Caller is expected to have
//     already called Stop.
//
// Production Linux deployments still use RealSystemctl; selection is via
// the RM_API_SYSTEMD_BACKEND env var read in cmd/radius-manager-api/main.go.
type SupervisordSystemctl struct {
	// ConfDir is where program confs are written.
	// Default: /etc/supervisor/conf.d (Debian convention).
	ConfDir string

	// Bin is the supervisorctl binary path. Default: "supervisorctl".
	Bin string

	// FreeradiusUser is the system user the program should run as.
	// Default: "root" (matches the systemd unit emitted by manager).
	FreeradiusUser string
}

// NewSupervisordSystemctl returns a SupervisordSystemctl with the
// Debian-supervisor default paths.
func NewSupervisordSystemctl() *SupervisordSystemctl {
	return &SupervisordSystemctl{
		ConfDir:        "/etc/supervisor/conf.d",
		Bin:            "supervisorctl",
		FreeradiusUser: "root",
	}
}

// programName drops the trailing ".service" so "mitra_x-api.service"
// becomes the supervisord program "mitra_x-api". Returns the input
// unchanged when there is no suffix to drop.
func programName(unitName string) string {
	return strings.TrimSuffix(unitName, ".service")
}

// confPath returns the on-disk path of the supervisord conf for a unit.
func (s *SupervisordSystemctl) confPath(unitName string) string {
	return filepath.Join(s.ConfDir, programName(unitName)+".conf")
}

// bin returns the supervisorctl binary path with a default.
func (s *SupervisordSystemctl) bin() string {
	if s.Bin == "" {
		return "supervisorctl"
	}
	return s.Bin
}

// parsedUnit holds the subset of the systemd unit grammar we translate.
type parsedUnit struct {
	ExecStart        string
	WorkingDirectory string
	User             string
	Restart          string
}

// parseSystemdUnit pulls the few fields we need out of a unit file.
// We do not implement a full systemd parser — only Key=Value lines under
// the [Service] section.
func parseSystemdUnit(content string) parsedUnit {
	var u parsedUnit
	inService := false
	for _, raw := range strings.Split(content, "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			inService = strings.EqualFold(line, "[Service]")
			continue
		}
		if !inService {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		v = strings.TrimSpace(v)
		switch strings.TrimSpace(k) {
		case "ExecStart":
			u.ExecStart = v
		case "WorkingDirectory":
			u.WorkingDirectory = v
		case "User":
			u.User = v
		case "Restart":
			u.Restart = v
		}
	}
	return u
}

// WriteUnit translates a systemd unit into a supervisord program conf
// and writes it to ConfDir/<name>.conf. It does NOT run reread/update;
// callers must invoke DaemonReload (or supervisord will pick up the
// change on its next reread).
func (s *SupervisordSystemctl) WriteUnit(_ context.Context, unitName, content string) error {
	parsed := parseSystemdUnit(content)
	if parsed.ExecStart == "" {
		return fmt.Errorf("supervisord: unit %q has no ExecStart= under [Service]", unitName)
	}
	user := parsed.User
	if user == "" {
		user = s.FreeradiusUser
		if user == "" {
			user = "root"
		}
	}
	autorestart := "true"
	if strings.EqualFold(parsed.Restart, "no") {
		autorestart = "false"
	}

	prog := programName(unitName)
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "; Auto-generated by radius-manager-api from systemd unit %s.\n", unitName)
	fmt.Fprintf(&buf, "; Edits will be overwritten — modify the manager template instead.\n")
	fmt.Fprintf(&buf, "[program:%s]\n", prog)
	fmt.Fprintf(&buf, "command=%s\n", parsed.ExecStart)
	if parsed.WorkingDirectory != "" {
		fmt.Fprintf(&buf, "directory=%s\n", parsed.WorkingDirectory)
	}
	fmt.Fprintf(&buf, "user=%s\n", user)
	fmt.Fprintf(&buf, "autorestart=%s\n", autorestart)
	fmt.Fprintf(&buf, "autostart=true\n")
	fmt.Fprintf(&buf, "startsecs=3\n")
	fmt.Fprintf(&buf, "stopasgroup=true\n")
	fmt.Fprintf(&buf, "killasgroup=true\n")
	fmt.Fprintf(&buf, "stdout_logfile=/var/log/supervisor/%s.out.log\n", prog)
	fmt.Fprintf(&buf, "stderr_logfile=/var/log/supervisor/%s.err.log\n", prog)

	if err := os.MkdirAll(s.ConfDir, 0o755); err != nil {
		return fmt.Errorf("supervisord: mkdir %s: %w", s.ConfDir, err)
	}
	return os.WriteFile(s.confPath(unitName), buf.Bytes(), 0o644)
}

// RemoveUnit deletes the supervisord conf for the unit. Idempotent.
// Callers should have already issued Stop so supervisord doesn't
// continue tracking a stale program after the conf is gone.
func (s *SupervisordSystemctl) RemoveUnit(_ context.Context, unitName string) error {
	err := os.Remove(s.confPath(unitName))
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// run is the workhorse for shelling out to supervisorctl.
func (s *SupervisordSystemctl) run(ctx context.Context, args ...string) (string, error) {
	cmd := exec.CommandContext(ctx, s.bin(), args...)
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &out
	err := cmd.Run()
	return out.String(), err
}

// DaemonReload tells supervisord to reread its configs and apply changes
// (start newly-defined programs, stop removed ones).
func (s *SupervisordSystemctl) DaemonReload(ctx context.Context) error {
	if out, err := s.run(ctx, "reread"); err != nil {
		return fmt.Errorf("supervisorctl reread: %w; output: %s", err, out)
	}
	if out, err := s.run(ctx, "update"); err != nil {
		return fmt.Errorf("supervisorctl update: %w; output: %s", err, out)
	}
	return nil
}

// Enable is a no-op for supervisord — autorestart=true in the conf
// already covers "start automatically" semantics.
func (s *SupervisordSystemctl) Enable(_ context.Context, _ string) error { return nil }

// Disable is a no-op for the same reason as Enable.
func (s *SupervisordSystemctl) Disable(_ context.Context, _ string) error { return nil }

func (s *SupervisordSystemctl) Start(ctx context.Context, unitName string) error {
	prog := programName(unitName)
	if out, err := s.run(ctx, "start", prog); err != nil {
		return fmt.Errorf("supervisorctl start %s: %w; output: %s", prog, err, out)
	}
	return nil
}

func (s *SupervisordSystemctl) Stop(ctx context.Context, unitName string) error {
	prog := programName(unitName)
	if out, err := s.run(ctx, "stop", prog); err != nil {
		// supervisorctl stop returns non-zero if the program isn't running;
		// treat the "not running" case as success to keep teardown idempotent.
		if strings.Contains(out, "not running") || strings.Contains(out, "ERROR (no such process)") {
			return nil
		}
		return fmt.Errorf("supervisorctl stop %s: %w; output: %s", prog, err, out)
	}
	return nil
}

func (s *SupervisordSystemctl) Restart(ctx context.Context, unitName string) error {
	prog := programName(unitName)
	if out, err := s.run(ctx, "restart", prog); err != nil {
		return fmt.Errorf("supervisorctl restart %s: %w; output: %s", prog, err, out)
	}
	return nil
}

func (s *SupervisordSystemctl) IsActive(ctx context.Context, unitName string) (bool, error) {
	prog := programName(unitName)
	out, err := s.run(ctx, "status", prog)
	if err != nil {
		// supervisorctl status exit codes:
		//   0 = process is RUNNING
		//   3 = process is STOPPED / FATAL / etc. (still a valid response)
		// We use stdout text as the source of truth instead because the
		// exact exit-code semantics differ across versions.
		if strings.Contains(out, "RUNNING") {
			return true, nil
		}
		if strings.Contains(out, "STOPPED") ||
			strings.Contains(out, "FATAL") ||
			strings.Contains(out, "EXITED") ||
			strings.Contains(out, "STARTING") {
			return false, nil
		}
		return false, fmt.Errorf("supervisorctl status %s: %w; output: %s", prog, err, out)
	}
	return strings.Contains(out, "RUNNING"), nil
}

// SupervisordFreeRADIUS is a FreeRADIUS controller backed by supervisord.
// It restarts the freeradius program managed by supervisord (the daemon
// runs as a child of supervisord in the Docker dev image).
type SupervisordFreeRADIUS struct {
	Systemctl *SupervisordSystemctl
	Program   string // default "freeradius"
}

// NewSupervisordFreeRADIUS returns a controller with sensible defaults.
func NewSupervisordFreeRADIUS(s *SupervisordSystemctl) *SupervisordFreeRADIUS {
	return &SupervisordFreeRADIUS{Systemctl: s, Program: "freeradius"}
}

func (f *SupervisordFreeRADIUS) program() string {
	if f.Program == "" {
		return "freeradius"
	}
	return f.Program
}

// Reload restarts the freeradius supervisord program. FreeRADIUS doesn't
// support live reload via signals when launched by supervisord, so we
// match the existing RealFreeRADIUS behavior of full restart.
func (f *SupervisordFreeRADIUS) Reload(ctx context.Context) error {
	return f.Systemctl.Restart(ctx, f.program())
}

// Restart is identical to Reload for supervisord-managed freeradius.
func (f *SupervisordFreeRADIUS) Restart(ctx context.Context) error {
	return f.Systemctl.Restart(ctx, f.program())
}
